trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: my-app-repo
  IMAGE_TAG: $(Build.BuildId)

steps:

- checkout: self

# Login + get account ID (OIDC)
- task: AWSShellScript@1
  displayName: AWS Login + Get Account ID
  inputs:
    awsCredentials: 'aws-oidc-role'
    regionName: '$(AWS_REGION)'
    scriptType: inline
    inlineScript: |

      ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      echo "ACCOUNT_ID=$ACCOUNT_ID"

      aws ecr get-login-password --region $(AWS_REGION) | \
      docker login --username AWS --password-stdin \
      $ACCOUNT_ID.dkr.ecr.$(AWS_REGION).amazonaws.com

      echo "##vso[task.setvariable variable=ACCOUNT_ID]$ACCOUNT_ID"

# Build image
- script: |
    docker build -t $(ECR_REPOSITORY):$(IMAGE_TAG) .
  displayName: Build Docker Image

# Tag image
- script: |
    docker tag $(ECR_REPOSITORY):$(IMAGE_TAG) \
    $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(IMAGE_TAG)
  displayName: Tag Docker Image

# Push image
- script: |
    docker push \
    $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(IMAGE_TAG)
  displayName: Push Docker Image
