apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: prod-oce
spec:
  type: {{ .Values.service.type }}

  selector:
    app: hello-world

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
